Content:
    moltres:
        root_dir: ${ROOT_DIR}/doc/content
    moose:
        root_dir: ${MOOSE_DIR}/framework/doc/content
        content:
            - js/*
            - css/*
            - contrib/**
            - media/**
            - templates/stubs/*

Renderer:
    type: MooseDocs.base.MaterializeRenderer

Extensions:
    MooseDocs.extensions.template:
        active: True
    MooseDocs.extensions.navigation:
        name: Moltres
        repo: https://github.com/arfc/moltres
        menu:
            Getting Started: getting_started.md
            Documentation: source/index.md
            Help: help.md
            Citing: citing.md
    MooseDocs.extensions.appsyntax:
        executable: ${ROOT_DIR}
        remove: !include ${MOOSE_DIR}/framework/doc/remove.yml
        includes:
            - include
